### PR TITLE
Add Room Preview Demo

### PR DESCRIPTION
**Pull request by niravcodes**

### CODE REVIEW

**Comment by danieleds** [comment]
@niravcodes are you going to add the REST way of getting room previews in this PR?

**Comment by niravcodes** [comment]
@danieleds I thought this demo could stand on its own. The REST API demo wouldn't be as straightforward as this, so that will live in a separate folder.

**Comment by danieleds** [comment]
@niravcodes could you add a readme with basic instructions to run this? For example, saying that this should be served from a webserver on localhost. A handy npm start script would be nice

**Comment by danieleds** [comment]
@niravcodes could you add a readme with basic instructions to run this? For example, saying that this should be served from a webserver on localhost. A handy npm start script would be nice

**Review by danieleds — DISMISSED** [review]

**Review by danieleds — APPROVED** [review]

**Pull request merged**
